name: Load Raw Data like artifact to wandb

on:
  push:
    branches:
      - main
    paths:
      - 'src/data/load.py'

jobs:
  load_data:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Actualizado a la versión que soporta Node.js 20
    - name: Set up Python
      uses: actions/setup-python@v5  # Actualizado a la versión que soporta Node.js 20
      id: setup
      with:
        python-version: '3.9'
        cache: 'pip'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Login to WandB
      run: wandb login ${{ secrets.WANDB_API_KEY }}
    - name: Run load.py
      run: python src/data/load.py --IdExecution ${{ github.run_number }}
